# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mqTEvNra31_0zBC8c5ilBeBAq7a5oHcJ
"""

# Community Food Sharing System

# List to store all donated food
food_list = []


# Function to donate food
def donate_food():
    print("Donate Food")

    food_name = input("Food Name: ")
    quantity = input("Quantity: ")
    category = input("Category: ")
    location = input("Location: ")

    food = {
        "Food Name": food_name,
        "Quantity": quantity,
        "Category": category,
        "Location": location
    }

    food_list.append(food)
    print("Food Added Successfully")


# Function to view all food
def view_food():
    print("Available Food")

    if len(food_list) == 0:
        print("No food has been donated yet")
    else:
        for i, food in enumerate(food_list, start=1):
            print(f"Food Item {i}")
            print("Food Name :", food["Food Name"])
            print("Quantity  :", food["Quantity"])
            print("Category  :", food["Category"])
            print("Location  :", food["Location"])
        print()


# Function to search food by category
def search_food():
    print("search Food")

    search_category = input("Enter Category: ")

    found = False

    for food in food_list:
        if food["Category"].lower() == search_category.lower():
            print("Food Found")
            print("Food Name :", food["Food Name"])
            print("Quantity  :", food["Quantity"])
            print("Category  :", food["Category"])
            print("Location  :", food["Location"])
            found = True

    if not found:
        print("No Food Found")

    print()


# Main Menu
while True:

    print(" Community Food Sharing System")
    print("1. Donate Food")
    print("2. View Food")
    print("3. Search Food")
    print("4. Exit")

    choice = input("Enter Choice: ")

    if choice == "1":
        donate_food()

    elif choice == "2":
        view_food()

    elif choice == "3":
        search_food()

    elif choice == "4":
        print("Thank You!")
        break

    else:
        print("Invalid Choice! Please try again")

